# Generated by Django 5.2 on 2025-10-03 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del evento')),
                ('descripcion', models.TextField(verbose_name='Descripción del evento')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('capacidad_maxima', models.PositiveIntegerField(default=100, verbose_name='Capacidad máxima')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='borrador', max_length=20, verbose_name='Estado del evento')),
                ('privacidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=20, verbose_name='Tipo de privacidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen del evento')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de entrada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_inicio'],
                'permissions': [('can_view_private_events', 'Puede ver eventos privados'), ('can_manage_all_events', 'Puede gestionar todos los eventos')],
            },
        ),
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del registro')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='eventos.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Evento',
                'verbose_name_plural': 'Registros de Eventos',
                'ordering': ['-fecha_registro'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='eventos_asistiendo', through='eventos.RegistroEvento', to=settings.AUTH_USER_MODEL, verbose_name='Asistentes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.tipoevento', verbose_name='Tipo de evento'),
        ),
    ]
